# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactionHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=255, null=True)),
                ('iban', models.CharField(max_length=255)),
                ('swift', models.CharField(max_length=255)),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
